{{ range $attributes := .Values.nodes }}
{{ if $attributes.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: amaru-{{ $attributes.name }}
  labels:
    app: amaru
spec:
  selector:
    app: amaru
    name: {{ $attributes.name }}
    type: {{ $attributes.type }}
    network: {{ $.Values.network }}
  ports:
    - protocol: TCP
      name: node
      port: {{ $attributes.port }}
      targetPort: node
  clusterIP: None
  type: ClusterIP
{{ if $attributes.nodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: amaru-{{ $attributes.name }}-ext
  labels:
    app: amaru
spec:
  selector:
    app: amaru
    name: {{ $attributes.name }}
    type: {{ $attributes.type }}
    network: {{ $.Values.network }}
  ports:
    - protocol: TCP
      name: node
      port: {{ $attributes.port }}
      targetPort: node
      nodePort: {{ $attributes.nodePort }}
    {{- $collectorConfig := $attributes.otelCollector | default $.Values.otelCollector }}
    {{- if $collectorConfig.enabled }}
    - protocol: TCP
      name: otel-prom
      port: {{ $collectorConfig.prometheusPort | default 9464 }}
      targetPort: prometheus
    {{- else }}
    - protocol: TCP
      name: prom
      port: 12798
    {{- end }}
    {{- if $attributes.socatEnabled }}
    - protocol: TCP
      name: socat
      port: {{ $attributes.socatPort }}
      targetPort: socat
    {{- end }}
  type: NodePort
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: amaru-{{ $attributes.name }}-int
  labels:
    app: amaru
spec:
  selector:
    app: amaru
    name: {{ $attributes.name }}
    type: {{ $attributes.type }}
    network: {{ $.Values.network }}
  ports:
    - protocol: TCP
      name: node
      port: {{ $attributes.port }}
      targetPort: node
    {{- $collectorConfig := $attributes.otelCollector | default $.Values.otelCollector }}
    {{- if $collectorConfig.enabled }}
    - protocol: TCP
      name: otel-prom
      port: {{ $collectorConfig.prometheusPort | default 9464 }}
      targetPort: prometheus
    {{- else }}
    - protocol: TCP
      name: prom
      port: 12798
    {{- end }}
    {{- if $attributes.socatEnabled }}
    - protocol: TCP
      name: socat
      port: {{ $attributes.socatPort }}
      targetPort: socat
    {{- end }}
  type: ClusterIP
{{ if and $attributes.socatEnabled $attributes.socatNodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: amaru-{{ $attributes.name }}-socat
  labels:
    app: amaru
spec:
  selector:
    app: amaru
    name: {{ $attributes.name }}
    type: {{ $attributes.type }}
    network: {{ $.Values.network }}
  ports:
    - protocol: TCP
      name: socat
      port: {{ $attributes.socatPort }}
      nodePort: {{ $attributes.socatNodePort }}
  type: NodePort
{{ end }}
{{ end }}
{{ end }}
