{{ if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cardano-node-service-monitor
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - path: /metrics
      port: prom
      scrapeProtocols:
        - PrometheusText0.0.4
        - OpenMetricsText1.0.0
        - OpenMetricsText0.0.1
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: cardano-node
{{ end }}
